version: '3'
services:
  monitoreo:
    build: ./prometheus_monitoreo/prometheus_exporter
    network_mode: "host"

  iotbridge:
    build: ./iotbridge
    image: hernancontigiani/iotbridge:latest
    restart: always
    network_mode: "host"

    volumes: 
      - /home/logs/iotbridge:/home/logs/iotbridge

    env_file:
      - .env